### ISSUE TITLE
Error starting the app.

### ISSUE THREAD

**Issue by wpoosanguansit** [jonasbuntinx/next-purescript-example#1]
Hi,

I followed the steps in your README.md but I do get this error:

Module not found: Can't resolve '../output/App/index.js' in '~/next-purescript-example/pages'

Should the output be auto generated or should it be created manually?  Thanks.

**Comment by jonasbuntinx** [comment]
Have you tried ‘yarn build’?

**Comment by wpoosanguansit** [comment]
Thanks Jonas.  I clone the repo again and cleaned out everything before I rebuilt the project.  This time everything was generated correctly, I think.  Now it is running.

**Comment by jonasbuntinx** [comment]
I have updated the README.md with the build command that builds the existing pages. The hot reloading only builds pages when their files are changed.
